// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pantiltMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pantiltMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* pantiltMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pantiltMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pantiltMessage_2eproto() {
  protobuf_AddDesc_pantiltMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pantiltMessage.proto");
  GOOGLE_CHECK(file != NULL);
  pantiltMessage_descriptor_ = file->message_type(0);
  static const int pantiltMessage_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pantiltMessage, online_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pantiltMessage, pan_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pantiltMessage, tilt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pantiltMessage, zoom_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pantiltMessage, foucs_),
  };
  pantiltMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      pantiltMessage_descriptor_,
      pantiltMessage::default_instance_,
      pantiltMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pantiltMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pantiltMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(pantiltMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pantiltMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    pantiltMessage_descriptor_, &pantiltMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pantiltMessage_2eproto() {
  delete pantiltMessage::default_instance_;
  delete pantiltMessage_reflection_;
}

void protobuf_AddDesc_pantiltMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024pantiltMessage.proto\"X\n\016pantiltMessage"
    "\022\016\n\006online\030\001 \001(\005\022\013\n\003pan\030\002 \001(\005\022\014\n\004tilt\030\003 "
    "\001(\005\022\014\n\004zoom\030\004 \001(\005\022\r\n\005foucs\030\005 \001(\005", 112);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pantiltMessage.proto", &protobuf_RegisterTypes);
  pantiltMessage::default_instance_ = new pantiltMessage();
  pantiltMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pantiltMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pantiltMessage_2eproto {
  StaticDescriptorInitializer_pantiltMessage_2eproto() {
    protobuf_AddDesc_pantiltMessage_2eproto();
  }
} static_descriptor_initializer_pantiltMessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int pantiltMessage::kOnlineFieldNumber;
const int pantiltMessage::kPanFieldNumber;
const int pantiltMessage::kTiltFieldNumber;
const int pantiltMessage::kZoomFieldNumber;
const int pantiltMessage::kFoucsFieldNumber;
#endif  // !_MSC_VER

pantiltMessage::pantiltMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void pantiltMessage::InitAsDefaultInstance() {
}

pantiltMessage::pantiltMessage(const pantiltMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void pantiltMessage::SharedCtor() {
  _cached_size_ = 0;
  online_ = 0;
  pan_ = 0;
  tilt_ = 0;
  zoom_ = 0;
  foucs_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

pantiltMessage::~pantiltMessage() {
  SharedDtor();
}

void pantiltMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void pantiltMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pantiltMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pantiltMessage_descriptor_;
}

const pantiltMessage& pantiltMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pantiltMessage_2eproto();
  return *default_instance_;
}

pantiltMessage* pantiltMessage::default_instance_ = NULL;

pantiltMessage* pantiltMessage::New() const {
  return new pantiltMessage;
}

void pantiltMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    online_ = 0;
    pan_ = 0;
    tilt_ = 0;
    zoom_ = 0;
    foucs_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool pantiltMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 online = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &online_)));
          set_has_online();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_pan;
        break;
      }

      // optional int32 pan = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_pan:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pan_)));
          set_has_pan();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_tilt;
        break;
      }

      // optional int32 tilt = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_tilt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tilt_)));
          set_has_tilt();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_zoom;
        break;
      }

      // optional int32 zoom = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_zoom:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &zoom_)));
          set_has_zoom();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_foucs;
        break;
      }

      // optional int32 foucs = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_foucs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &foucs_)));
          set_has_foucs();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void pantiltMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 online = 1;
  if (has_online()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->online(), output);
  }

  // optional int32 pan = 2;
  if (has_pan()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->pan(), output);
  }

  // optional int32 tilt = 3;
  if (has_tilt()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->tilt(), output);
  }

  // optional int32 zoom = 4;
  if (has_zoom()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->zoom(), output);
  }

  // optional int32 foucs = 5;
  if (has_foucs()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->foucs(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* pantiltMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 online = 1;
  if (has_online()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->online(), target);
  }

  // optional int32 pan = 2;
  if (has_pan()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->pan(), target);
  }

  // optional int32 tilt = 3;
  if (has_tilt()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->tilt(), target);
  }

  // optional int32 zoom = 4;
  if (has_zoom()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->zoom(), target);
  }

  // optional int32 foucs = 5;
  if (has_foucs()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->foucs(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int pantiltMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 online = 1;
    if (has_online()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->online());
    }

    // optional int32 pan = 2;
    if (has_pan()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->pan());
    }

    // optional int32 tilt = 3;
    if (has_tilt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->tilt());
    }

    // optional int32 zoom = 4;
    if (has_zoom()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->zoom());
    }

    // optional int32 foucs = 5;
    if (has_foucs()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->foucs());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pantiltMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const pantiltMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const pantiltMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void pantiltMessage::MergeFrom(const pantiltMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_online()) {
      set_online(from.online());
    }
    if (from.has_pan()) {
      set_pan(from.pan());
    }
    if (from.has_tilt()) {
      set_tilt(from.tilt());
    }
    if (from.has_zoom()) {
      set_zoom(from.zoom());
    }
    if (from.has_foucs()) {
      set_foucs(from.foucs());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void pantiltMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pantiltMessage::CopyFrom(const pantiltMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pantiltMessage::IsInitialized() const {

  return true;
}

void pantiltMessage::Swap(pantiltMessage* other) {
  if (other != this) {
    std::swap(online_, other->online_);
    std::swap(pan_, other->pan_);
    std::swap(tilt_, other->tilt_);
    std::swap(zoom_, other->zoom_);
    std::swap(foucs_, other->foucs_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata pantiltMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pantiltMessage_descriptor_;
  metadata.reflection = pantiltMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
