# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AlarmMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AlarmMessage.proto',
  package='',
  serialized_pb='\n\x12\x41larmMessage.proto\"\xbe\x01\n\x0c\x41larmMessage\x12\x1c\n\x14\x43trolBoxHighTemAlarm\x18\x01 \x01(\x08\x12\x1e\n\x16\x43trolBoxFrozenTemAlarm\x18\x02 \x01(\x08\x12\x1a\n\x12\x42MSModComLostAlarm\x18\x03 \x01(\x08\x12\x1d\n\x15\x45mergency_Status_stop\x18\x04 \x01(\x08\x12\x1d\n\x15\x45\x63\x61nExternSnsorNdeOFF\x18\x05 \x01(\x08\x12\x16\n\x0eJoyTestNodeOFF\x18\x07 \x01(\x08')




_ALARMMESSAGE = _descriptor.Descriptor(
  name='AlarmMessage',
  full_name='AlarmMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CtrolBoxHighTemAlarm', full_name='AlarmMessage.CtrolBoxHighTemAlarm', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CtrolBoxFrozenTemAlarm', full_name='AlarmMessage.CtrolBoxFrozenTemAlarm', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BMSModComLostAlarm', full_name='AlarmMessage.BMSModComLostAlarm', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Emergency_Status_stop', full_name='AlarmMessage.Emergency_Status_stop', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EcanExternSnsorNdeOFF', full_name='AlarmMessage.EcanExternSnsorNdeOFF', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='JoyTestNodeOFF', full_name='AlarmMessage.JoyTestNodeOFF', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['AlarmMessage'] = _ALARMMESSAGE

class AlarmMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALARMMESSAGE

  # @@protoc_insertion_point(class_scope:AlarmMessage)


# @@protoc_insertion_point(module_scope)
