# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ControllerMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ExternSensor_pb2
import BMSMessage_pb2
import ErrorMessage_pb2
import AlarmMessage_pb2
import UltrasoundMessage_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ControllerMessage.proto',
  package='',
  serialized_pb='\n\x17\x43ontrollerMessage.proto\x1a\x12\x45xternSensor.proto\x1a\x10\x42MSMessage.proto\x1a\x12\x45rrorMessage.proto\x1a\x12\x41larmMessage.proto\x1a\x17UltrasoundMessage.proto\"\x91\x04\n\x11\x43ontrollerMessage\x12\x0c\n\x04Stat\x18\x01 \x01(\x05\x12\x30\n\rDirverMessage\x18\x02 \x03(\x0b\x32\x19.ControllerMessage.Dirver\x12 \n\tSensorMsg\x18\x03 \x01(\x0b\x32\r.ExternSensor\x12\x13\n\x0b\x63trl_device\x18\x04 \x01(\x05\x12\x1b\n\x06\x62msMsg\x18\x05 \x01(\x0b\x32\x0b.BmsMessage\x12\x1f\n\x08\x65rrormsg\x18\x06 \x01(\x0b\x32\r.ErrorMessage\x12\x1f\n\x08\x61larmmsg\x18\x07 \x01(\x0b\x32\r.AlarmMessage\x12&\n\nUltrasound\x18\x08 \x01(\x0b\x32\x12.UltrasoundMessage\x12\x14\n\x0cLineVelocity\x18\t \x01(\x02\x12\x12\n\nTHVelocity\x18\n \x01(\x02\x1a\xd3\x01\n\x06\x44irver\x12\x15\n\rdevice_status\x18\x01 \x01(\x05\x12\x12\n\ndevice_add\x18\x02 \x01(\x05\x12\x13\n\x0b\x41\x63tVelocity\x18\x03 \x01(\x05\x12\x13\n\x0bSetVelocity\x18\x04 \x01(\x05\x12\x17\n\x0f\x63trl_dc_Voltage\x18\x05 \x01(\x02\x12\x1c\n\x14\x43TRL_IPM_TEMPERATURE\x18\x06 \x01(\x02\x12\x11\n\tActualPos\x18\x07 \x01(\x05\x12\x1b\n\x13\x45mergencyInputValue\x18\x08 \x01(\x08\x12\r\n\x05\x45rror\x18\t \x01(\t')




_CONTROLLERMESSAGE_DIRVER = _descriptor.Descriptor(
  name='Dirver',
  full_name='ControllerMessage.Dirver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_status', full_name='ControllerMessage.Dirver.device_status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_add', full_name='ControllerMessage.Dirver.device_add', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ActVelocity', full_name='ControllerMessage.Dirver.ActVelocity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SetVelocity', full_name='ControllerMessage.Dirver.SetVelocity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ctrl_dc_Voltage', full_name='ControllerMessage.Dirver.ctrl_dc_Voltage', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CTRL_IPM_TEMPERATURE', full_name='ControllerMessage.Dirver.CTRL_IPM_TEMPERATURE', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ActualPos', full_name='ControllerMessage.Dirver.ActualPos', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EmergencyInputValue', full_name='ControllerMessage.Dirver.EmergencyInputValue', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Error', full_name='ControllerMessage.Dirver.Error', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=449,
  serialized_end=660,
)

_CONTROLLERMESSAGE = _descriptor.Descriptor(
  name='ControllerMessage',
  full_name='ControllerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Stat', full_name='ControllerMessage.Stat', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DirverMessage', full_name='ControllerMessage.DirverMessage', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SensorMsg', full_name='ControllerMessage.SensorMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ctrl_device', full_name='ControllerMessage.ctrl_device', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bmsMsg', full_name='ControllerMessage.bmsMsg', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errormsg', full_name='ControllerMessage.errormsg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarmmsg', full_name='ControllerMessage.alarmmsg', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ultrasound', full_name='ControllerMessage.Ultrasound', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LineVelocity', full_name='ControllerMessage.LineVelocity', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='THVelocity', full_name='ControllerMessage.THVelocity', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CONTROLLERMESSAGE_DIRVER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=131,
  serialized_end=660,
)

_CONTROLLERMESSAGE_DIRVER.containing_type = _CONTROLLERMESSAGE;
_CONTROLLERMESSAGE.fields_by_name['DirverMessage'].message_type = _CONTROLLERMESSAGE_DIRVER
_CONTROLLERMESSAGE.fields_by_name['SensorMsg'].message_type = ExternSensor_pb2._EXTERNSENSOR
_CONTROLLERMESSAGE.fields_by_name['bmsMsg'].message_type = BMSMessage_pb2._BMSMESSAGE
_CONTROLLERMESSAGE.fields_by_name['errormsg'].message_type = ErrorMessage_pb2._ERRORMESSAGE
_CONTROLLERMESSAGE.fields_by_name['alarmmsg'].message_type = AlarmMessage_pb2._ALARMMESSAGE
_CONTROLLERMESSAGE.fields_by_name['Ultrasound'].message_type = UltrasoundMessage_pb2._ULTRASOUNDMESSAGE
DESCRIPTOR.message_types_by_name['ControllerMessage'] = _CONTROLLERMESSAGE

class ControllerMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Dirver(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLLERMESSAGE_DIRVER

    # @@protoc_insertion_point(class_scope:ControllerMessage.Dirver)
  DESCRIPTOR = _CONTROLLERMESSAGE

  # @@protoc_insertion_point(class_scope:ControllerMessage)


# @@protoc_insertion_point(module_scope)
