# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ErrorMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ErrorMessage.proto',
  package='',
  serialized_pb='\n\x12\x45rrorMessage.proto\"\xa5\x04\n\x0c\x45rrorMessage\x12\x1b\n\x13\x43\x61rLeftFDriverError\x18\x01 \x01(\x08\x12\x1c\n\x14\x43\x61rRightFDriverError\x18\x02 \x01(\x08\x12\x1b\n\x13\x43\x61rLeftBDriverError\x18\x03 \x01(\x08\x12\x1c\n\x14\x43\x61rRightBDriverError\x18\x04 \x01(\x08\x12\x1b\n\x13LeftFDriverComError\x18\x05 \x01(\x08\x12\x1c\n\x14RightFDriverComError\x18\x06 \x01(\x08\x12\x1b\n\x13LeftBDriverComError\x18\x07 \x01(\x08\x12\x1c\n\x14RightBDriverComError\x18\x08 \x01(\x08\x12\x19\n\x11\x45xternComDevError\x18\t \x01(\x08\x12\x13\n\x0b\x42MSSysError\x18\n \x01(\x08\x12\x19\n\x11ObstacleStopError\x18\x0b \x01(\x08\x12\x1b\n\x13\x43\x61shSwitchStopError\x18\x0c \x01(\x08\x12\x1c\n\x14\x43urrentOverloadError\x18\r \x01(\x08\x12\x1a\n\x12\x44riverLeftFNodeOFF\x18\x0e \x01(\x08\x12\x1a\n\x12\x44riverLeftBNodeOFF\x18\x0f \x01(\x08\x12\x1b\n\x13\x44riverRightFNodeOFF\x18\x10 \x01(\x08\x12\x1b\n\x13\x44riverRightBNodeOFF\x18\x11 \x01(\x08\x12\x1a\n\x12\x42ObstacleStopError\x18\x12 \x01(\x08\x12\x15\n\rDropStopError\x18\x13 \x01(\x08')




_ERRORMESSAGE = _descriptor.Descriptor(
  name='ErrorMessage',
  full_name='ErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CarLeftFDriverError', full_name='ErrorMessage.CarLeftFDriverError', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CarRightFDriverError', full_name='ErrorMessage.CarRightFDriverError', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CarLeftBDriverError', full_name='ErrorMessage.CarLeftBDriverError', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CarRightBDriverError', full_name='ErrorMessage.CarRightBDriverError', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LeftFDriverComError', full_name='ErrorMessage.LeftFDriverComError', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RightFDriverComError', full_name='ErrorMessage.RightFDriverComError', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LeftBDriverComError', full_name='ErrorMessage.LeftBDriverComError', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RightBDriverComError', full_name='ErrorMessage.RightBDriverComError', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ExternComDevError', full_name='ErrorMessage.ExternComDevError', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BMSSysError', full_name='ErrorMessage.BMSSysError', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ObstacleStopError', full_name='ErrorMessage.ObstacleStopError', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CashSwitchStopError', full_name='ErrorMessage.CashSwitchStopError', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CurrentOverloadError', full_name='ErrorMessage.CurrentOverloadError', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DriverLeftFNodeOFF', full_name='ErrorMessage.DriverLeftFNodeOFF', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DriverLeftBNodeOFF', full_name='ErrorMessage.DriverLeftBNodeOFF', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DriverRightFNodeOFF', full_name='ErrorMessage.DriverRightFNodeOFF', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DriverRightBNodeOFF', full_name='ErrorMessage.DriverRightBNodeOFF', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BObstacleStopError', full_name='ErrorMessage.BObstacleStopError', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DropStopError', full_name='ErrorMessage.DropStopError', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=572,
)

DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE

class ErrorMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ERRORMESSAGE

  # @@protoc_insertion_point(class_scope:ErrorMessage)


# @@protoc_insertion_point(module_scope)
