# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExternSensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExternSensor.proto',
  package='',
  serialized_pb='\n\x12\x45xternSensor.proto\"\xe2\x01\n\x0c\x45xternSensor\x12\x0e\n\x06online\x18\x08 \x01(\x05\x12\x12\n\nTemp_Pt100\x18\x01 \x03(\x05\x12/\n\tTemp_humi\x18\x02 \x03(\x0b\x32\x1c.ExternSensor.Mode_Temp_humi\x12\x13\n\x0bIO_Infrared\x18\x04 \x03(\x05\x12\x14\n\x0cIO_collision\x18\x05 \x03(\x05\x12\x12\n\nLED_status\x18\x06 \x01(\t\x1a>\n\x0eMode_Temp_humi\x12\x15\n\rinterior_temp\x18\x01 \x01(\x05\x12\x15\n\rinterior_humi\x18\x02 \x01(\x05')




_EXTERNSENSOR_MODE_TEMP_HUMI = _descriptor.Descriptor(
  name='Mode_Temp_humi',
  full_name='ExternSensor.Mode_Temp_humi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interior_temp', full_name='ExternSensor.Mode_Temp_humi.interior_temp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interior_humi', full_name='ExternSensor.Mode_Temp_humi.interior_humi', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=187,
  serialized_end=249,
)

_EXTERNSENSOR = _descriptor.Descriptor(
  name='ExternSensor',
  full_name='ExternSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='online', full_name='ExternSensor.online', index=0,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Temp_Pt100', full_name='ExternSensor.Temp_Pt100', index=1,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Temp_humi', full_name='ExternSensor.Temp_humi', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IO_Infrared', full_name='ExternSensor.IO_Infrared', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IO_collision', full_name='ExternSensor.IO_collision', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LED_status', full_name='ExternSensor.LED_status', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXTERNSENSOR_MODE_TEMP_HUMI, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=249,
)

_EXTERNSENSOR_MODE_TEMP_HUMI.containing_type = _EXTERNSENSOR;
_EXTERNSENSOR.fields_by_name['Temp_humi'].message_type = _EXTERNSENSOR_MODE_TEMP_HUMI
DESCRIPTOR.message_types_by_name['ExternSensor'] = _EXTERNSENSOR

class ExternSensor(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Mode_Temp_humi(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _EXTERNSENSOR_MODE_TEMP_HUMI

    # @@protoc_insertion_point(class_scope:ExternSensor.Mode_Temp_humi)
  DESCRIPTOR = _EXTERNSENSOR

  # @@protoc_insertion_point(class_scope:ExternSensor)


# @@protoc_insertion_point(module_scope)
