# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyserrorMessag.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SyserrorMessag.proto',
  package='',
  serialized_pb='\n\x14SyserrorMessag.proto')





# @@protoc_insertion_point(module_scope)
