// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pantiltMessage.proto

#ifndef PROTOBUF_pantiltMessage_2eproto__INCLUDED
#define PROTOBUF_pantiltMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pantiltMessage_2eproto();
void protobuf_AssignDesc_pantiltMessage_2eproto();
void protobuf_ShutdownFile_pantiltMessage_2eproto();

class pantiltMessage;

// ===================================================================

class pantiltMessage : public ::google::protobuf::Message {
 public:
  pantiltMessage();
  virtual ~pantiltMessage();

  pantiltMessage(const pantiltMessage& from);

  inline pantiltMessage& operator=(const pantiltMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const pantiltMessage& default_instance();

  void Swap(pantiltMessage* other);

  // implements Message ----------------------------------------------

  pantiltMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pantiltMessage& from);
  void MergeFrom(const pantiltMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 online = 1;
  inline bool has_online() const;
  inline void clear_online();
  static const int kOnlineFieldNumber = 1;
  inline ::google::protobuf::int32 online() const;
  inline void set_online(::google::protobuf::int32 value);

  // optional int32 pan = 2;
  inline bool has_pan() const;
  inline void clear_pan();
  static const int kPanFieldNumber = 2;
  inline ::google::protobuf::int32 pan() const;
  inline void set_pan(::google::protobuf::int32 value);

  // optional int32 tilt = 3;
  inline bool has_tilt() const;
  inline void clear_tilt();
  static const int kTiltFieldNumber = 3;
  inline ::google::protobuf::int32 tilt() const;
  inline void set_tilt(::google::protobuf::int32 value);

  // optional int32 zoom = 4;
  inline bool has_zoom() const;
  inline void clear_zoom();
  static const int kZoomFieldNumber = 4;
  inline ::google::protobuf::int32 zoom() const;
  inline void set_zoom(::google::protobuf::int32 value);

  // optional int32 foucs = 5;
  inline bool has_foucs() const;
  inline void clear_foucs();
  static const int kFoucsFieldNumber = 5;
  inline ::google::protobuf::int32 foucs() const;
  inline void set_foucs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pantiltMessage)
 private:
  inline void set_has_online();
  inline void clear_has_online();
  inline void set_has_pan();
  inline void clear_has_pan();
  inline void set_has_tilt();
  inline void clear_has_tilt();
  inline void set_has_zoom();
  inline void clear_has_zoom();
  inline void set_has_foucs();
  inline void clear_has_foucs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 online_;
  ::google::protobuf::int32 pan_;
  ::google::protobuf::int32 tilt_;
  ::google::protobuf::int32 zoom_;
  ::google::protobuf::int32 foucs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_pantiltMessage_2eproto();
  friend void protobuf_AssignDesc_pantiltMessage_2eproto();
  friend void protobuf_ShutdownFile_pantiltMessage_2eproto();

  void InitAsDefaultInstance();
  static pantiltMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// pantiltMessage

// optional int32 online = 1;
inline bool pantiltMessage::has_online() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void pantiltMessage::set_has_online() {
  _has_bits_[0] |= 0x00000001u;
}
inline void pantiltMessage::clear_has_online() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void pantiltMessage::clear_online() {
  online_ = 0;
  clear_has_online();
}
inline ::google::protobuf::int32 pantiltMessage::online() const {
  return online_;
}
inline void pantiltMessage::set_online(::google::protobuf::int32 value) {
  set_has_online();
  online_ = value;
}

// optional int32 pan = 2;
inline bool pantiltMessage::has_pan() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void pantiltMessage::set_has_pan() {
  _has_bits_[0] |= 0x00000002u;
}
inline void pantiltMessage::clear_has_pan() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void pantiltMessage::clear_pan() {
  pan_ = 0;
  clear_has_pan();
}
inline ::google::protobuf::int32 pantiltMessage::pan() const {
  return pan_;
}
inline void pantiltMessage::set_pan(::google::protobuf::int32 value) {
  set_has_pan();
  pan_ = value;
}

// optional int32 tilt = 3;
inline bool pantiltMessage::has_tilt() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void pantiltMessage::set_has_tilt() {
  _has_bits_[0] |= 0x00000004u;
}
inline void pantiltMessage::clear_has_tilt() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void pantiltMessage::clear_tilt() {
  tilt_ = 0;
  clear_has_tilt();
}
inline ::google::protobuf::int32 pantiltMessage::tilt() const {
  return tilt_;
}
inline void pantiltMessage::set_tilt(::google::protobuf::int32 value) {
  set_has_tilt();
  tilt_ = value;
}

// optional int32 zoom = 4;
inline bool pantiltMessage::has_zoom() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void pantiltMessage::set_has_zoom() {
  _has_bits_[0] |= 0x00000008u;
}
inline void pantiltMessage::clear_has_zoom() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void pantiltMessage::clear_zoom() {
  zoom_ = 0;
  clear_has_zoom();
}
inline ::google::protobuf::int32 pantiltMessage::zoom() const {
  return zoom_;
}
inline void pantiltMessage::set_zoom(::google::protobuf::int32 value) {
  set_has_zoom();
  zoom_ = value;
}

// optional int32 foucs = 5;
inline bool pantiltMessage::has_foucs() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void pantiltMessage::set_has_foucs() {
  _has_bits_[0] |= 0x00000010u;
}
inline void pantiltMessage::clear_has_foucs() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void pantiltMessage::clear_foucs() {
  foucs_ = 0;
  clear_has_foucs();
}
inline ::google::protobuf::int32 pantiltMessage::foucs() const {
  return foucs_;
}
inline void pantiltMessage::set_foucs(::google::protobuf::int32 value) {
  set_has_foucs();
  foucs_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pantiltMessage_2eproto__INCLUDED
