/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ExternSensor_2eproto__INCLUDED
#define PROTOBUF_C_ExternSensor_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ExternSensor ExternSensor;
typedef struct _ExternSensor__ModeTempHumi ExternSensor__ModeTempHumi;


/* --- enums --- */


/* --- messages --- */

struct  _ExternSensor__ModeTempHumi
{
  ProtobufCMessage base;
  protobuf_c_boolean has_interior_temp;
  int32_t interior_temp;
  protobuf_c_boolean has_interior_humi;
  int32_t interior_humi;
};
#define EXTERN_SENSOR__MODE__TEMP_HUMI__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&extern_sensor__mode__temp_humi__descriptor) \
    , 0,0, 0,0 }


struct  _ExternSensor
{
  ProtobufCMessage base;
  protobuf_c_boolean has_online;
  int32_t online;
  size_t n_temp_pt100;
  int32_t *temp_pt100;
  size_t n_temp_humi;
  ExternSensor__ModeTempHumi **temp_humi;
  size_t n_io_infrared;
  int32_t *io_infrared;
  size_t n_io_collision;
  int32_t *io_collision;
  char *led_status;
};
#define EXTERN_SENSOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&extern_sensor__descriptor) \
    , 0,0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL }


/* ExternSensor__ModeTempHumi methods */
void   extern_sensor__mode__temp_humi__init
                     (ExternSensor__ModeTempHumi         *message);
/* ExternSensor methods */
void   extern_sensor__init
                     (ExternSensor         *message);
size_t extern_sensor__get_packed_size
                     (const ExternSensor   *message);
size_t extern_sensor__pack
                     (const ExternSensor   *message,
                      uint8_t             *out);
size_t extern_sensor__pack_to_buffer
                     (const ExternSensor   *message,
                      ProtobufCBuffer     *buffer);
ExternSensor *
       extern_sensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   extern_sensor__free_unpacked
                     (ExternSensor *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ExternSensor__ModeTempHumi_Closure)
                 (const ExternSensor__ModeTempHumi *message,
                  void *closure_data);
typedef void (*ExternSensor_Closure)
                 (const ExternSensor *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor extern_sensor__descriptor;
extern const ProtobufCMessageDescriptor extern_sensor__mode__temp_humi__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ExternSensor_2eproto__INCLUDED */
