/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_RobotStatusMessage_2eproto__INCLUDED
#define PROTOBUF_C_RobotStatusMessage_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "ControllerMessage.pb-c.h"
#include "pantiltMessage.pb-c.h"

typedef struct _RobotStatusMessage RobotStatusMessage;
typedef struct _RobotStatusMessage__Camera RobotStatusMessage__Camera;
typedef struct _RobotStatusMessage__Infredcamera RobotStatusMessage__Infredcamera;


/* --- enums --- */


/* --- messages --- */

struct  _RobotStatusMessage__Camera
{
  ProtobufCMessage base;
  protobuf_c_boolean has_online;
  int32_t online;
};
#define ROBOT_STATUS_MESSAGE__CAMERA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot_status_message__camera__descriptor) \
    , 0,0 }


struct  _RobotStatusMessage__Infredcamera
{
  ProtobufCMessage base;
  protobuf_c_boolean has_online;
  int32_t online;
};
#define ROBOT_STATUS_MESSAGE__INFREDCAMERA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot_status_message__infredcamera__descriptor) \
    , 0,0 }


struct  _RobotStatusMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_stat;
  int32_t stat;
  ControllerMessage *controller;
  RobotStatusMessage__Camera *cameramsg;
  RobotStatusMessage__Infredcamera *infredcameramsg;
  PantiltMessage *pantlitmsg;
};
#define ROBOT_STATUS_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&robot_status_message__descriptor) \
    , 0,0, NULL, NULL, NULL, NULL }


/* RobotStatusMessage__Camera methods */
void   robot_status_message__camera__init
                     (RobotStatusMessage__Camera         *message);
/* RobotStatusMessage__Infredcamera methods */
void   robot_status_message__infredcamera__init
                     (RobotStatusMessage__Infredcamera         *message);
/* RobotStatusMessage methods */
void   robot_status_message__init
                     (RobotStatusMessage         *message);
size_t robot_status_message__get_packed_size
                     (const RobotStatusMessage   *message);
size_t robot_status_message__pack
                     (const RobotStatusMessage   *message,
                      uint8_t             *out);
size_t robot_status_message__pack_to_buffer
                     (const RobotStatusMessage   *message,
                      ProtobufCBuffer     *buffer);
RobotStatusMessage *
       robot_status_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   robot_status_message__free_unpacked
                     (RobotStatusMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RobotStatusMessage__Camera_Closure)
                 (const RobotStatusMessage__Camera *message,
                  void *closure_data);
typedef void (*RobotStatusMessage__Infredcamera_Closure)
                 (const RobotStatusMessage__Infredcamera *message,
                  void *closure_data);
typedef void (*RobotStatusMessage_Closure)
                 (const RobotStatusMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor robot_status_message__descriptor;
extern const ProtobufCMessageDescriptor robot_status_message__camera__descriptor;
extern const ProtobufCMessageDescriptor robot_status_message__infredcamera__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_RobotStatusMessage_2eproto__INCLUDED */
