/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_BMSMessage_2eproto__INCLUDED
#define PROTOBUF_C_BMSMessage_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _BmsMessage BmsMessage;


/* --- enums --- */


/* --- messages --- */

struct  _BmsMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_stat;
  int32_t stat;
  protobuf_c_boolean has_bms_soc;
  int32_t bms_soc;
  protobuf_c_boolean has_bms_voltage;
  float bms_voltage;
  protobuf_c_boolean has_bms_sys_current;
  float bms_sys_current;
};
#define BMS_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bms_message__descriptor) \
    , 0,0, 0,0, 0,0, 0,0 }


/* BmsMessage methods */
void   bms_message__init
                     (BmsMessage         *message);
size_t bms_message__get_packed_size
                     (const BmsMessage   *message);
size_t bms_message__pack
                     (const BmsMessage   *message,
                      uint8_t             *out);
size_t bms_message__pack_to_buffer
                     (const BmsMessage   *message,
                      ProtobufCBuffer     *buffer);
BmsMessage *
       bms_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bms_message__free_unpacked
                     (BmsMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BmsMessage_Closure)
                 (const BmsMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor bms_message__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_BMSMessage_2eproto__INCLUDED */
