/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "BMSMessage.pb-c.h"
void   bms_message__init
                     (BmsMessage         *message)
{
  static BmsMessage init_value = BMS_MESSAGE__INIT;
  *message = init_value;
}
size_t bms_message__get_packed_size
                     (const BmsMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bms_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bms_message__pack
                     (const BmsMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bms_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bms_message__pack_to_buffer
                     (const BmsMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bms_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BmsMessage *
       bms_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BmsMessage *)
     protobuf_c_message_unpack (&bms_message__descriptor,
                                allocator, len, data);
}
void   bms_message__free_unpacked
                     (BmsMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bms_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bms_message__field_descriptors[4] =
{
  {
    "Stat",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(BmsMessage, has_stat),
    PROTOBUF_C_OFFSETOF(BmsMessage, stat),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BMS_SOC",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(BmsMessage, has_bms_soc),
    PROTOBUF_C_OFFSETOF(BmsMessage, bms_soc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BMS_Voltage",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(BmsMessage, has_bms_voltage),
    PROTOBUF_C_OFFSETOF(BmsMessage, bms_voltage),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BMS_sys_Current",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(BmsMessage, has_bms_sys_current),
    PROTOBUF_C_OFFSETOF(BmsMessage, bms_sys_current),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bms_message__field_indices_by_name[] = {
  1,   /* field[1] = BMS_SOC */
  2,   /* field[2] = BMS_Voltage */
  3,   /* field[3] = BMS_sys_Current */
  0,   /* field[0] = Stat */
};
static const ProtobufCIntRange bms_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor bms_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "BmsMessage",
  "BmsMessage",
  "BmsMessage",
  "",
  sizeof(BmsMessage),
  4,
  bms_message__field_descriptors,
  bms_message__field_indices_by_name,
  1,  bms_message__number_ranges,
  (ProtobufCMessageInit) bms_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
