/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "pantiltMessage.pb-c.h"
void   pantilt_message__init
                     (PantiltMessage         *message)
{
  static PantiltMessage init_value = PANTILT_MESSAGE__INIT;
  *message = init_value;
}
size_t pantilt_message__get_packed_size
                     (const PantiltMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pantilt_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pantilt_message__pack
                     (const PantiltMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pantilt_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pantilt_message__pack_to_buffer
                     (const PantiltMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pantilt_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PantiltMessage *
       pantilt_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PantiltMessage *)
     protobuf_c_message_unpack (&pantilt_message__descriptor,
                                allocator, len, data);
}
void   pantilt_message__free_unpacked
                     (PantiltMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pantilt_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pantilt_message__field_descriptors[5] =
{
  {
    "online",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PantiltMessage, has_online),
    PROTOBUF_C_OFFSETOF(PantiltMessage, online),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pan",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PantiltMessage, has_pan),
    PROTOBUF_C_OFFSETOF(PantiltMessage, pan),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tilt",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PantiltMessage, has_tilt),
    PROTOBUF_C_OFFSETOF(PantiltMessage, tilt),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoom",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PantiltMessage, has_zoom),
    PROTOBUF_C_OFFSETOF(PantiltMessage, zoom),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "foucs",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(PantiltMessage, has_foucs),
    PROTOBUF_C_OFFSETOF(PantiltMessage, foucs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pantilt_message__field_indices_by_name[] = {
  4,   /* field[4] = foucs */
  0,   /* field[0] = online */
  1,   /* field[1] = pan */
  2,   /* field[2] = tilt */
  3,   /* field[3] = zoom */
};
static const ProtobufCIntRange pantilt_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor pantilt_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "pantiltMessage",
  "PantiltMessage",
  "PantiltMessage",
  "",
  sizeof(PantiltMessage),
  5,
  pantilt_message__field_descriptors,
  pantilt_message__field_indices_by_name,
  1,  pantilt_message__number_ranges,
  (ProtobufCMessageInit) pantilt_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
