/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "UltrasoundMessage.pb-c.h"
void   ultrasound_message__init
                     (UltrasoundMessage         *message)
{
  static UltrasoundMessage init_value = ULTRASOUND_MESSAGE__INIT;
  *message = init_value;
}
size_t ultrasound_message__get_packed_size
                     (const UltrasoundMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ultrasound_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ultrasound_message__pack
                     (const UltrasoundMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ultrasound_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ultrasound_message__pack_to_buffer
                     (const UltrasoundMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ultrasound_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UltrasoundMessage *
       ultrasound_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UltrasoundMessage *)
     protobuf_c_message_unpack (&ultrasound_message__descriptor,
                                allocator, len, data);
}
void   ultrasound_message__free_unpacked
                     (UltrasoundMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ultrasound_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ultrasound_message__field_descriptors[3] =
{
  {
    "online",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(UltrasoundMessage, has_online),
    PROTOBUF_C_OFFSETOF(UltrasoundMessage, online),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ldistance_Ultrasonic",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(UltrasoundMessage, has_ldistance_ultrasonic),
    PROTOBUF_C_OFFSETOF(UltrasoundMessage, ldistance_ultrasonic),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Rdistance_Ultrasonic",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(UltrasoundMessage, has_rdistance_ultrasonic),
    PROTOBUF_C_OFFSETOF(UltrasoundMessage, rdistance_ultrasonic),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ultrasound_message__field_indices_by_name[] = {
  1,   /* field[1] = Ldistance_Ultrasonic */
  2,   /* field[2] = Rdistance_Ultrasonic */
  0,   /* field[0] = online */
};
static const ProtobufCIntRange ultrasound_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ultrasound_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "UltrasoundMessage",
  "UltrasoundMessage",
  "UltrasoundMessage",
  "",
  sizeof(UltrasoundMessage),
  3,
  ultrasound_message__field_descriptors,
  ultrasound_message__field_indices_by_name,
  1,  ultrasound_message__number_ranges,
  (ProtobufCMessageInit) ultrasound_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
