/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_pantiltMessage_2eproto__INCLUDED
#define PROTOBUF_C_pantiltMessage_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _PantiltMessage PantiltMessage;


/* --- enums --- */


/* --- messages --- */

struct  _PantiltMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_online;
  int32_t online;
  protobuf_c_boolean has_pan;
  int32_t pan;
  protobuf_c_boolean has_tilt;
  int32_t tilt;
  protobuf_c_boolean has_zoom;
  int32_t zoom;
  protobuf_c_boolean has_foucs;
  int32_t foucs;
};
#define PANTILT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pantilt_message__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0 }


/* PantiltMessage methods */
void   pantilt_message__init
                     (PantiltMessage         *message);
size_t pantilt_message__get_packed_size
                     (const PantiltMessage   *message);
size_t pantilt_message__pack
                     (const PantiltMessage   *message,
                      uint8_t             *out);
size_t pantilt_message__pack_to_buffer
                     (const PantiltMessage   *message,
                      ProtobufCBuffer     *buffer);
PantiltMessage *
       pantilt_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pantilt_message__free_unpacked
                     (PantiltMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PantiltMessage_Closure)
                 (const PantiltMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pantilt_message__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_pantiltMessage_2eproto__INCLUDED */
