// Generated by gencpp from file dgvmsg/remoter.msg
// DO NOT EDIT!


#ifndef DGVMSG_MESSAGE_REMOTER_H
#define DGVMSG_MESSAGE_REMOTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dgvmsg/Vector3.h>
#include <dgvmsg/Vector3.h>

namespace dgvmsg
{
template <class ContainerAllocator>
struct remoter_
{
  typedef remoter_<ContainerAllocator> Type;

  remoter_()
    : header()
    , online(0)
    , linear()
    , angular()
    , IOSTATUES1()
    , IOSTATUES2()
    , buttons()  {
    }
  remoter_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , online(0)
    , linear(_alloc)
    , angular(_alloc)
    , IOSTATUES1(_alloc)
    , IOSTATUES2(_alloc)
    , buttons(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _online_type;
  _online_type online;

   typedef  ::dgvmsg::Vector3_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::dgvmsg::Vector3_<ContainerAllocator>  _angular_type;
  _angular_type angular;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _IOSTATUES1_type;
  _IOSTATUES1_type IOSTATUES1;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _IOSTATUES2_type;
  _IOSTATUES2_type IOSTATUES2;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _buttons_type;
  _buttons_type buttons;




  typedef boost::shared_ptr< ::dgvmsg::remoter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dgvmsg::remoter_<ContainerAllocator> const> ConstPtr;

}; // struct remoter_

typedef ::dgvmsg::remoter_<std::allocator<void> > remoter;

typedef boost::shared_ptr< ::dgvmsg::remoter > remoterPtr;
typedef boost::shared_ptr< ::dgvmsg::remoter const> remoterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dgvmsg::remoter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dgvmsg::remoter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dgvmsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'dgvmsg': ['/home/pc-robot/Workspace/demo/roscpp/src/dgvmsg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dgvmsg::remoter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dgvmsg::remoter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dgvmsg::remoter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dgvmsg::remoter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dgvmsg::remoter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dgvmsg::remoter_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dgvmsg::remoter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb64999f0a6539f1e1247da4c560559b";
  }

  static const char* value(const ::dgvmsg::remoter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb64999f0a6539f1ULL;
  static const uint64_t static_value2 = 0xe1247da4c560559bULL;
};

template<class ContainerAllocator>
struct DataType< ::dgvmsg::remoter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dgvmsg/remoter";
  }

  static const char* value(const ::dgvmsg::remoter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dgvmsg::remoter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 online\n\
Vector3  linear\n\
Vector3  angular\n\
uint8[] IOSTATUES1\n\
uint8[] IOSTATUES2\n\
uint8[] buttons\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: dgvmsg/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::dgvmsg::remoter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dgvmsg::remoter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.online);
      stream.next(m.linear);
      stream.next(m.angular);
      stream.next(m.IOSTATUES1);
      stream.next(m.IOSTATUES2);
      stream.next(m.buttons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remoter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dgvmsg::remoter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dgvmsg::remoter_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "online: ";
    Printer<int16_t>::stream(s, indent + "  ", v.online);
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::dgvmsg::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::dgvmsg::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
    s << indent << "IOSTATUES1[]" << std::endl;
    for (size_t i = 0; i < v.IOSTATUES1.size(); ++i)
    {
      s << indent << "  IOSTATUES1[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.IOSTATUES1[i]);
    }
    s << indent << "IOSTATUES2[]" << std::endl;
    for (size_t i = 0; i < v.IOSTATUES2.size(); ++i)
    {
      s << indent << "  IOSTATUES2[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.IOSTATUES2[i]);
    }
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.buttons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DGVMSG_MESSAGE_REMOTER_H
