// Generated by gencpp from file dgvmsg/remoterctrl.msg
// DO NOT EDIT!


#ifndef DGVMSG_MESSAGE_REMOTERCTRL_H
#define DGVMSG_MESSAGE_REMOTERCTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dgvmsg
{
template <class ContainerAllocator>
struct remoterctrl_
{
  typedef remoterctrl_<ContainerAllocator> Type;

  remoterctrl_()
    : header()
    , ctrl_autodoor(0)  {
    }
  remoterctrl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ctrl_autodoor(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _ctrl_autodoor_type;
  _ctrl_autodoor_type ctrl_autodoor;




  typedef boost::shared_ptr< ::dgvmsg::remoterctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dgvmsg::remoterctrl_<ContainerAllocator> const> ConstPtr;

}; // struct remoterctrl_

typedef ::dgvmsg::remoterctrl_<std::allocator<void> > remoterctrl;

typedef boost::shared_ptr< ::dgvmsg::remoterctrl > remoterctrlPtr;
typedef boost::shared_ptr< ::dgvmsg::remoterctrl const> remoterctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dgvmsg::remoterctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dgvmsg::remoterctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dgvmsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'dgvmsg': ['/home/pc-robot/Workspace/demo/roscpp/src/dgvmsg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dgvmsg::remoterctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dgvmsg::remoterctrl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dgvmsg::remoterctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dgvmsg::remoterctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dgvmsg::remoterctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dgvmsg::remoterctrl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dgvmsg::remoterctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6a1b8e6b5fe4720ee6fb42f38d46646";
  }

  static const char* value(const ::dgvmsg::remoterctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6a1b8e6b5fe4720ULL;
  static const uint64_t static_value2 = 0xee6fb42f38d46646ULL;
};

template<class ContainerAllocator>
struct DataType< ::dgvmsg::remoterctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dgvmsg/remoterctrl";
  }

  static const char* value(const ::dgvmsg::remoterctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dgvmsg::remoterctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 ctrl_autodoor\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dgvmsg::remoterctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dgvmsg::remoterctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ctrl_autodoor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remoterctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dgvmsg::remoterctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dgvmsg::remoterctrl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ctrl_autodoor: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ctrl_autodoor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DGVMSG_MESSAGE_REMOTERCTRL_H
